#ref https://cert-manager.io/docs/configuration/acme/dns01/#setting-nameservers-for-dns01-self-check
extraArgs: 
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53