apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nkzk
  namespace: vcluster
spec:
  secretName: nkzk-no-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - nkzk
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always # recommended
  usages:
    - server auth
    - client auth
  dnsNames:
    - nkzk.no
    - "*.nkzk.no"
  issuerRef:
    name: cloudflare-nkzk
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io