apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-nkzk
spec:
  acme:
    email: nkzk95@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory # staging-server. prod: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-issuer-account-key
    solvers:
    - dns01:
        cnameStrategy: Follow
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token